version: "3.5"

services:
  setup:
    container_name: twilight-setup
    image: phpswoole/swoole:php8.2
    command: [ "composer", "install" ]
    working_dir: /var/www
    volumes:
      - .:/var/www
  
  api1: &api
    container_name: twilight-app1
    image: phpswoole/swoole:php8.2
    restart: unless-stopped
    environment:
      - APP_ENV=development
      - AUTORELOAD_PROGRAMS=swoole
      - AUTORELOAD_ANY_FILES=0
      - CACHE_HOST=cache
      - CACHE_PORT=6379
      - DB_DSN=mysql:host=db;dbname=twilight
      - DB_USER=root
      - DB_PASSWORD=root
      - LOG_MAX_SIZE=100000
      - LOG_MAX_FILES=3
      - LOG_LEVEL=Debug
#       Debug
#       Info
#       Notice
#       Warning
#       Error
#       Critical
#       Alert
#       Emergency
    depends_on:
      - cache
      - db
    working_dir: /var/www
    volumes:
      - .:/var/www
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "500MB"
  
  api2:
    <<: *api
    container_name: twilight-app2
  
  nginx:
    container_name: twilight-reverse-proxy
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "500MB"
  
  cache:
    container_name: twilight-cache
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "500MB"
  
  db:
    container_name: twilight-database
    image: mysql:8.1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=twilight
    volumes:
#      - ./docker/db/twilight.sql:/var/www/twilight.sql
      - ./docker/db/twilight.sql:/docker-entrypoint-initdb.d/migrations.sql
      - ./docker/db/.my.cnf:/root/.my.cnf
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1000MB"

networks:
  default:
    name: twilight
