version: "3.5"

services:
  setup:
    container_name: twilight-setup
    image: phpswoole/swoole:php8.2
    command: [ "composer", "install" ]
    working_dir: /var/www
    volumes:
      - .:/var/www
  
  api1: &api
    container_name: twilight-app1
    image: phpswoole/swoole:php8.2
    environment:
      APP_ENV: development
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    working_dir: /var/www
    volumes:
      - .:/var/www
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "750MB"
  
  api2:
    <<: *api
    container_name: twilight-app2
  
  nginx:
    image: nginx
    container_name: twilight-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "500MB"

networks:
  default:
    name: twilight
